name: Test workflow

on: [push]

jobs:
  output_comment:
    runs-on: [ "self-hosted" ]
    steps: 
      - name: comment out
        run: |
          echo "hello world"
      - name: move-test
        run: |
          Move-Item ./.github/sample ./.github/workflows
          Get-ChildItem
  
  check_folder:
    runs-on: [ "self-hosted" ]
    steps: 
      - name: check_folder
        run: |
          Get-ChildItem
  
      
      