name: Test workflow

on: 
  workflow_dispatch:
    inputs:
      bottun:
        type: choice
        description: select mode
        required: true
        default: 'Text'
        options: 
        - Test
        

jobs:
  output_comment:
    runs-on: [ "self-hosted" ]
    steps: 
      - name: comment out
        run: |
          echo "hello world"
