name: Test workflow

on: 
  workflow_dispatch:
    inputs:
      bottun:
        type: choice
        description: select mode
        required: true
        default: 'Text'
        options: 
        - Text
        

jobs:
  output_comment:
    runs-on: [ "self-hosted" ]
    steps: 
      - name: comment out
        run: |
          echo "hello world2"
      - name: upload file
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: .\input\sample.txt
      
