name: Test workflow

on: 
  workflow_dispatch:
    inputs:
      bottun:
        type: string
        description: select mode
        required: true
        default: 'Text'

        

jobs:
  output_comment:
    runs-on: [ "self-hosted" ]
    steps: 
      - name: comment out
        run: |
          echo "hello world"
      - name: upload file
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: .\input\sample.txt
      
